### ISSUE TITLE
Angle brackets in docstrings

### ISSUE THREAD

**Issue by xuhcc** [pawamoy/mkdocstrings#108]
When I'm building module documentation with `mkdocstrings`, I get the following error:

```
mkdocstrings.extension: mismatched tag: line 3029, column 49 (character p):
        <td><p>A string of <number> <currency>.</p></td>
If your Markdown contains angle brackets < >, try to wrap them between backticks `< >`, or replace them with &lt; and &gt;
ERROR   -  Error reading page 'api_reference/module.md': mismatched tag: line 3029, column 49 
```

<details>
<summary>Traceback</summary>
<pre>
Traceback (most recent call last):
  File "/venv/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/venv/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/mkdocs/__main__.py", line 140, in serve_command
    serve.serve(
  File "/venv/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/venv/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/venv/lib/python3.8/site-packages/mkdocs/structure/pages.py", line 183, in render
    self.content = md.convert(self.markdown)
  File "/venv/lib/python3.8/site-packages/markdown/core.py", line 263, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/venv/lib/python3.8/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/venv/lib/python3.8/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/venv/lib/python3.8/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/venv/lib/python3.8/site-packages/mkdocstrings/extension.py", line 168, in run
    as_xml = XML(rendered)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 3029, column 49
</pre>
</details>

Indeed there were angle brackets in the docstring, but unfortunately I can't change the source code at the moment. Is there any workaround?

`mkdocstrings` version: 0.11.0

**Comment by pawamoy** [comment]
OK so in this case, it's not really the angle brackets that are an issue, it's that `<td><p>A string of <number> <currency>.</p></td>` is parsed as XML, and since the `number` and `currency` tags were opended, the XML parser expected to see `</currency>` and `</number>` before `</p>`.

There's unfortunately no workaround at this time.

I'll try to see if I can make the XML parser more tolerant to tag mismatches.

In any case, I (and Markdown parsers) consider the following markup `<td><p>A string of <number> <currency>.</p></td>` to be invalid Markdown, and so it should be fixed in your upstream as one of the following:

- <code>&lt;td&gt;&lt;p&gt;A string of \`&lt;number&gt; &lt;currency&gt;\`.&lt;/p&gt;&lt;/td&gt;</code> should work
- `<td><p>A string of <code>number currency</code>.</p></td>` works
- `<td><p>A string of &lt;number&gt; &lt;currency&gt;.</p></td>` works

They could also simply consider using other characters or formatting:

- `<td><p>A string of [number] [currency].</p></td>`

**Comment by xuhcc** [comment]
The docstring in the source code doesn't contain `<p>` and `<td>` tags:

```
Args:
    string: A string of <number> <currency>.
```

I think they were added during the build process.

>There's unfortunately no workaround at this time.

Is it possible to subclass/override default python handler and add some postprocessing to it (e.g. replace `<` with `&lt;`)? That would work for me.

>I'll try to see if I can make the XML parser more tolerant to tag mismatches.

That would help too, thanks!

**Comment by pawamoy** [comment]
Ah sorry, I misunderstood. Well I'd recommend the maintainers to change it to <code>string: A string of \`&lt;number&gt; &lt;currency&gt;\`.</code>, though I understand it might not be possible (upstream project or dependency not using mkdocstrings, and so not using markdown, etc.)

I checked the code of the XML parser and I can't see any options allowing to make it tolerant to tag mismatches :confused:  We can always pass it another Parser class with custom behavior, but I absolutely don't feel like writing one haha :sweat_smile:

About processing the intermediary result: I think it would be very hard as well, if not impossible. How do you know which `<` and `>` should be replaced? They could appear in a lot of places where they are legitimate and should not be escaped.

Of course we could add options to always escape angle brackets in docstrings contents, but I feel like this is overkill, prone to error, and so easily fixed with proper markup instead :confused:

**Comment by xuhcc** [comment]
>(Edit: I assumed you didn't have access to the source code when you said "I can't change the source code at the moment", but maybe you just can't do it now)

It is an open-source project that is maintained by another person and it is in the process of migration to another hosting platform. So changing the source is not an option right now :smile: 

>About processing the intermediary result: I think it would be very hard as well, if not impossible. How do you know which < and > should be replaced? They could appear in a lot of places where they are legitimate and should not be escaped.

As a temporary workaround, I would simply replace all angle brackets in docstrings.

**Comment by pawamoy** [comment]
You can always patch your installed mkdocstrings then! In `mkdocstrings/handlers/python.py`, then in `rebuild_category_lists`, something like this:

```python
for section in obj["docstring_sections"]:
    stype = section["type"]
    if stype == "markdown":
        section["value"] = section[" value"].replace("<", "&lt;").replace(">", "&gt;")
    elif stype == "parameter":
        for p in section["value"]:
            p["description"] = ...
```

I'm on mobile right now, will give you the full snippet later if you need, meanwhile just check what the sections look like in pytkdocs/parsers/docstrings.py :)

**Comment by xuhcc** [comment]
Thank you, that worked. Here's the code if someone else will come here looking for solution:

```python
def rebuild_category_lists(obj: dict) -> None:
    obj["attributes"] = [obj["children"][path] for path in obj["attributes"]]
    obj["classes"] = [obj["children"][path] for path in obj["classes"]]
    obj["functions"] = [obj["children"][path] for path in obj["functions"]]
    obj["methods"] = [obj["children"][path] for path in obj["methods"]]
    obj["modules"] = [obj["children"][path] for path in obj["modules"]]
    obj["children"] = [v for k, v in obj["children"].items()]
    for child in obj["children"]:
        rebuild_category_lists(child)

    # Workaround for https://github.com/pawamoy/mkdocstrings/issues/108
    for section in obj['docstring_sections']:
        if section['type'] == 'markdown':
            section['value'] = section['value'].\
                replace('<', '&lt;').\
                replace('>', '&gt;')
        elif section['type'] == 'parameters':
            for item in section['value']:
                item['description'] = item['description'].\
                    replace('<', '&lt;').\
                    replace('>', '&gt;')
        elif section['type'] == 'return':
            section['value']['description'] = section['value']['description'].\
                replace('<', '&lt;').\
                replace('>', '&gt;')
```

**Comment by pawamoy** [comment]
I'll go ahead and close this then since there's nothing more actionable here :slightly_smiling_face: 

And thank you very much for coming back and posting the whole workaround snippet!
