### ISSUE TITLE
Variable Documentation

### ISSUE THREAD

**Issue by daniel-butler** [pawamoy/mkdocstrings#119]
Is it possible to display variables like the dictionary below?

```python
COMMAND_HANDLERS = {
    commands.UpdateStatus: update_status,
    commands.NotifyAdmin: notify_admin,
    ....
}
```
I would like to show the variable's source, I could copy it into the documentation, but it very likely to be forgotten when updated making the documentation outdated. I would like it to display the source for this variable, An added bonus would be to the ability to link it to the other pieces of code with the [function][package.module.function] syntax.

Edit: I found a way to put [inline docstrings for variables](http://epydoc.sourceforge.net/manual-docstring.html). Not sure if it is outdated:

**Comment by pawamoy** [comment]
Attribute docstrings are recognized, yes. By attribute, I mean

- a module attribute (a variable declared in the module scope)
- a class attribute
- an instance attribute (scanned in the `__init__` method of its class)

Getting the source code for arbitrary variables would be quite complicated, as `inspect` cannot return their source or line numbers. It means we would have to parse the code, and I would like to avoid that as much as possible.

You could maybe use an enum instead of a dict, as their attributes will be auto-documented (though there is room for improvement).

**Comment by StephenBrown2** [comment]
+1 on using Enum. Documentation should be grabbed from those just like any class:
```
class COMMAND_HANDLERS(Enum)
    """Docstring for the command handlers."""
    commands.UpdateStatus = update_status
    commands.NotifyAdmin = notify_admin
    ...
```

By default `Enum`s documentation string is `An enumeration.`, but you can make it whatever you like easily.

**Comment by pawamoy** [comment]
Also, soon the `Attributes` section in docstrings will also be recognized, so you'll be able to do something like this:

```python
class CommandHandlers(enum.Enum):
    """
    Description of this enum.

    Attributes:
        UPDATE_STATUS: Update status handler description.
        NOTIFY_ADMIN: Notify admin handler description.
    """

    UPDATE_STATUS = update_status
    NOTIFY_ADMIN = notify_admin
```

...instead of

```python
class CommandHandlers(enum.Enum):
    """Description of this enum."""

    UPDATE_STATUS = update_status
    """Update status handler description."""

    NOTIFY_ADMIN = notify_admin
    """Notify admin handler description."""
```

**Comment by pawamoy** [comment]
I'll go ahead and close this, feel free to keep commenting though, or re-open if you feel your question is not answered!
