### ISSUE TITLE
How to handle bullet list in python docstrings

### ISSUE THREAD

**Issue by charlielito** [pawamoy/mkdocstrings#135]
Hi! I'm trying to list something inside the docstrings of an argument of a function. For example:

```python
def fn(
       x: tp.Union[
            jnp.ndarray,
            np.ndarray,
            tp.Mapping[str, tp.Union[np.ndarray, jnp.ndarray]],
            tp.Tuple[tp.Union[np.ndarray, jnp.ndarray]],
            tp.Iterable,
        ]   
    ):
        """
        function
        Arguments:
            x: Input data. It could be
                    - A Numpy or Jax array (or array-like), or a list of arrays
                    - A dict mapping input names to the corresponding arrays,
                    - A generator returning `(inputs,)`, `(inputs, targets)`
        """
```
Nonetheless, the documentation does not show it as a bullet list. How could this be achieved?
Thanks in advance!

**Comment by pawamoy** [comment]
Try this:

```python
def fn(
       x: tp.Union[
            jnp.ndarray,
            np.ndarray,
            tp.Mapping[str, tp.Union[np.ndarray, jnp.ndarray]],
            tp.Tuple[tp.Union[np.ndarray, jnp.ndarray]],
            tp.Iterable,
        ]   
    ):
        """
        function

        Arguments:
            x: Input data. It could be

                - A Numpy or Jax array (or array-like), or a list of arrays
                - A dict mapping input names to the corresponding arrays,
                - A generator returning `(inputs,)`, `(inputs, targets)`
        """
```

Explanation:

- New line after `function`: this is just to follow the PEP257 convention
- New line after `It could be`: the Python Markdown parser can be quite sensitive to new lines before/after bullet lists depending on which extension is loaded or not. I myself always add a blank line before and after bullet lists, just to be sure it's parsed correctly.
- Indentation: the bullet points have 4 more spaces of indentation than the `x: ` line, because they are continuation line for the `x` parameter description. I think you originally had 8, which would be parsed as a code block :slightly_smiling_face:

**Comment by charlielito** [comment]
Thanks! That works!!
