### ISSUE TITLE
How to document subpackages?

### ISSUE THREAD

**Issue by btjanaka** [pawamoy/mkdocstrings#168]
Hi there, let me start off by saying this is a great package, and I look forward to seeing where it goes.

I am trying to document a project that has subpackages in it (i.e. subdirectories), and I can't seem to get the subpackage members to appear. For instance, I have the following directory structure:

```
.
├── docs
│   ├── css
│   │   └── mkdocstrings.css
│   └── index.md
├── foo
│   ├── bar
│   │   ├── _baz.py
│   │   └── __init__.py
│   └── __init__.py
└── mkdocs.yml
```

With the following files:

- `foo/__init__.py`
  ```python
  import foo.bar
  ```
- `foo/bar/__init__.py`
  ```python
   from foo.bar._baz import Baz

  __all__ = [
      "Baz",
  ]
  ```
- `foo/bar/_baz.py`
  ```python
  class Baz:
      """This is my super awesome class."""
  ```
- `docs/index.md`
  ```python
  ::: foo.bar
  ```
- `mkdocs.yml`
  ```yml
  site_name: FooBar
  nav:
    - Home: index.md
  plugins:
    - search
    - mkdocstrings
  theme:
    name: material
  extra_css:
    - css/mkdocstrings.css
  ```

Essentially, I have a package named `foo`, and a subpackage named `foo.bar` that has a class named `Baz`. Furthermore, I have placed `Baz` in a separate file and imported it in `foo/bar/__init__.py`. Now, when I run `mkdocs serve`, I would expect that `index.html` would show the documentation for `foo.bar.Baz`. However, it does not, as shown below. Do you know why this is the case?

![image](https://user-images.githubusercontent.com/38124174/97770565-a6a1e380-1af1-11eb-8636-ec525260ce62.png)

Some things I have tried:
- If I add `filters: []` to `index.md`, `Baz` shows up, but as `foo.bar._baz.Baz` rather than `foo.bar.Baz` -- I suppose this is because the private members are no longer ignored.
- If I move `Baz` into `foo/bar/__init__.py`, it shows up. However, I want to be able to split my classes across multiple files, so this is not ideal.
- Adding `members: Baz` in `index.md` does not do anything; it seems `mkdcostrings` does not see `Baz` at all.

I wonder if this has something to do with how the Python handler interprets `__all__`, but I am not really sure how the handler works. If there is a proper way to handle this situation (maybe I missed an option somewhere?), or if there is a workaround, please let me know. Thanks!

**Add detailed information, like**
- project folder structure: see above
- `mkdocs.yml` configuration file contents: see above
- `mkdocstrings` version: 1.1.2

**Comment by pawamoy** [comment]
Hello!

`pytkdocs`, the package responsible for loading the objects data through introspection, resolves each object's path to get the real module where the object was defined. This is why what you're trying to do does not work, because `Baz` was not defined in `foo.bar` but in `foor.bar._baz`.

This behavior is necessary for attributes, because we need to know where the attribute is defined so we can parse its potential docstring and annotations. However I think it would be better if we kept this "real path" in an additional field, because it's not really needed for types of objects other than attributes, and I understand the use case here of defining things in sub-,private modules and import them in public facing ones.

I'll open the relevant feature request and close this if you don't mind :slightly_smiling_face:

**Comment by btjanaka** [comment]
Sounds good, thank you!
