### ISSUE TITLE
Can't run mkdocstrings repo

### ISSUE THREAD

**Issue by weilai-cv** [pawamoy/mkdocstrings#215]
Something broke today. Try and clone this repo and run `mkdocs serve`. You get this error

```bash
ERROR   -  Config value: 'plugins'. Error: The "mkdocstrings" plugin is not installed
```

Tried with all previous repositories that worked yesterday and also all broken when reinstalling virtualenv.

"mkdocs==1.1"
"mkdocs-material==6.2.3"
"mkdocstrings==0.14.0"

@pawamoy, this might have to do with a commit from today? None of my other dependencies changed.

Also when I ran yesterday, the default style did not have indentation lines or spacing between functions like [this](https://pawamoy.github.io/mkdocstrings/reference/plugin/#mkdocstrings.plugin.MkdocstringsPlugin.on_config). Do you know how I can achieve this?

**Comment by pawamoy** [comment]
The only commits of these last few days are updating documentation, so I don't think they broke anything :slightly_smiling_face: 

Could you try to uninstall mkdocstrings completely, and reinstall it? `pip uninstall -y mkdocstrings && pip install mkdocstrings==0.14.0`? Or maybe even recreate your virtualenv? We went from normal package to namespace package (0.13.6 to 0.14.0) and I'm not sure how upgrades behave.

**Comment by weilai-cv** [comment]
Something really weird is going on:

I recreate whole virtual environment and install everything and run `mkdocs serve` and I get this error:

```bash
INFO    -  Building documentation... 
ERROR   -  Config value: 'plugins'. Error: The "mkdocstrings" plugin is not installed 
```

Then all I do is `deactivate` and then come back inside virtualenv and run same command `mkdocs serve` and it all works...

**Comment by pawamoy** [comment]
Python mysteries! Some issues with old/new state of the environment while the virtualenv changed or something.
You write about deactivating virtualenv for mkdocstrings as well: note that this project is managed through Poetry, so you shouldn't have to play with virtualenvs yourself. Same thing for `pip install markdown-include`: `poetry install` takes care of installing it (it's correctly listed in the dev-dependencies section of pyproject.toml).

I'll close this since I don't think there's anything wrong on mkdocstrings' side :slightly_smiling_face:

**Comment by weilai-cv** [comment]
yup you're correct, I was not able to replicate this on another device. I will dig deeper and clean this. Thank you @pawamoy!

**Comment by pawamoy** [comment]
You're welcome!

**Comment by robcxyz** [comment]
I ran into this issue as well and @weilai-cv's comment about exiting venv then reactivating it solved it.

**Comment by pushfoo** [comment]
Exiting & reactivating the venv still works in 2024.
