### ISSUE TITLE
Autodoc enums

### ISSUE THREAD

**Issue by RDIL** [pawamoy/mkdocstrings#51]
Allow autodoc to parse enums:
```python
class MyEnum(enum.Enum):
    OPTION1 = "text"  #: Some PEP says this is a valid docstring
    OPTION2 = "other text"  #: This also!  
```

**Comment by pawamoy** [comment]
Instead of a comment, you can put a triple-quoted string below the variable. It will be picked up by mkdocstrings.

```python
class MyEnum(enum.Enum):
    OPTION1 = "text"
    """This is an actual docstring."""

    OPTION2 = "other text"
    """This also!""" 
```

I'm not willing to implement support for documentation in comments of the form `#:`, especially with the current state of the code, because we're using `ast` which does not parse comments. Later, when the structure is better and more stable, I'll be able to review PRs adding support for doc comments, type comments, etc., but they will probably need to be sent in another repository (the code will be split into different packages).

If you need more details about the roadmap, just ask 🙂 !

**Comment by RDIL** [comment]
If you are looking for another maintainer to help out, I'm happy to.  I believe in this project and would be willing to help it grow.

**Comment by pawamoy** [comment]
I'd absolutely love to have other maintainers on this project, thank you very much for offering your help :slightly_smiling_face:!

As stated in other comments, right now we're a bit stuck, but when the desired architecture is implemented, we'll be able to move faster. I'll tell you when this time comes, which I hope is soon!
